#!/usr/bin/env bash
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/ORION273-beep/DIPLOM}"
BLUEPRINT_URL="https://dashboard.render.com/blueprint/new?repo=${REPO_URL}"

echo ""
echo "════════════════════════════════════════════════════════"
echo "  OneSec — деплой на Render (без карты)"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  1. Откройте Blueprint:"
echo "     ${BLUEPRINT_URL}"
echo ""
echo "  2. Войдите через GitHub, если попросит"
echo "  3. Нажмите Apply и дождитесь сборки (~5–15 мин)"
echo ""
echo "  После деплоя:"
echo "    Сайт: https://orion-diplom-web.onrender.com"
echo "    API:  https://orion-diplom-api.onrender.com"
echo ""
echo "  Демо: fgf@mail.ru / demo123456"
echo "        fffff@mail.ru / admin123456"
echo "════════════════════════════════════════════════════════"
echo ""
